/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EnvtestRouteImport } from './routes/envtest'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateRouteImport } from './routes/create'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as SlugTimelineRouteImport } from './routes/$slug.timeline'
import { Route as SlugStoryRouteImport } from './routes/$slug.story'
import { Route as SlugRsvpRouteImport } from './routes/$slug.rsvp'
import { Route as SlugPlaylistRouteImport } from './routes/$slug.playlist'
import { Route as SlugLocationRouteImport } from './routes/$slug.location'
import { Route as SlugGuestbookRouteImport } from './routes/$slug.guestbook'
import { Route as SlugGalleryRouteImport } from './routes/$slug.gallery'
import { Route as SlugAdminRouteImport } from './routes/$slug.admin'
import { Route as AdminPlatformIndexRouteImport } from './routes/admin.platform.index'
import { Route as SlugAdminIndexRouteImport } from './routes/$slug.admin.index'
import { Route as AdminPlatformTodoTemplatesRouteImport } from './routes/admin.platform.todo-templates'
import { Route as AdminPlatformClaimRouteImport } from './routes/admin.platform.claim'
import { Route as SlugInviteCodeRouteImport } from './routes/$slug.invite.$code'
import { Route as SlugGalleryMeRouteImport } from './routes/$slug.gallery.me'
import { Route as SlugAdminTodoRouteImport } from './routes/$slug.admin.todo'
import { Route as SlugAdminTimelineRouteImport } from './routes/$slug.admin.timeline'
import { Route as SlugAdminStoryRouteImport } from './routes/$slug.admin.story'
import { Route as SlugAdminSettingsRouteImport } from './routes/$slug.admin.settings'
import { Route as SlugAdminSeatingRouteImport } from './routes/$slug.admin.seating'
import { Route as SlugAdminRsvpRouteImport } from './routes/$slug.admin.rsvp'
import { Route as SlugAdminPlaylistRouteImport } from './routes/$slug.admin.playlist'
import { Route as SlugAdminPhotosRouteImport } from './routes/$slug.admin.photos'
import { Route as SlugAdminInvitationRouteImport } from './routes/$slug.admin.invitation'
import { Route as SlugAdminGuestbookRouteImport } from './routes/$slug.admin.guestbook'
import { Route as SlugAdminBudgetRouteImport } from './routes/$slug.admin.budget'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvtestRoute = EnvtestRouteImport.update({
  id: '/envtest',
  path: '/envtest',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/admin/platform',
  path: '/admin/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugTimelineRoute = SlugTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStoryRoute = SlugStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => SlugRoute,
} as any)
const SlugRsvpRoute = SlugRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => SlugRoute,
} as any)
const SlugPlaylistRoute = SlugPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => SlugRoute,
} as any)
const SlugLocationRoute = SlugLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGuestbookRoute = SlugGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGalleryRoute = SlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRoute,
} as any)
const AdminPlatformIndexRoute = AdminPlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPlatformRoute,
} as any)
const SlugAdminIndexRoute = SlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugAdminRoute,
} as any)
const AdminPlatformTodoTemplatesRoute =
  AdminPlatformTodoTemplatesRouteImport.update({
    id: '/todo-templates',
    path: '/todo-templates',
    getParentRoute: () => AdminPlatformRoute,
  } as any)
const AdminPlatformClaimRoute = AdminPlatformClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => AdminPlatformRoute,
} as any)
const SlugInviteCodeRoute = SlugInviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGalleryMeRoute = SlugGalleryMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SlugGalleryRoute,
} as any)
const SlugAdminTodoRoute = SlugAdminTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminTimelineRoute = SlugAdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminStoryRoute = SlugAdminStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminSettingsRoute = SlugAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminSeatingRoute = SlugAdminSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminRsvpRoute = SlugAdminRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminPlaylistRoute = SlugAdminPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminPhotosRoute = SlugAdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminInvitationRoute = SlugAdminInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminGuestbookRoute = SlugAdminGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminBudgetRoute = SlugAdminBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => SlugAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/envtest': typeof EnvtestRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/admin': typeof SlugAdminRouteWithChildren
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/guestbook': typeof SlugGuestbookRoute
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/story': typeof SlugStoryRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/admin/platform': typeof AdminPlatformRouteWithChildren
  '/$slug/': typeof SlugIndexRoute
  '/$slug/admin/budget': typeof SlugAdminBudgetRoute
  '/$slug/admin/guestbook': typeof SlugAdminGuestbookRoute
  '/$slug/admin/invitation': typeof SlugAdminInvitationRoute
  '/$slug/admin/photos': typeof SlugAdminPhotosRoute
  '/$slug/admin/playlist': typeof SlugAdminPlaylistRoute
  '/$slug/admin/rsvp': typeof SlugAdminRsvpRoute
  '/$slug/admin/seating': typeof SlugAdminSeatingRoute
  '/$slug/admin/settings': typeof SlugAdminSettingsRoute
  '/$slug/admin/story': typeof SlugAdminStoryRoute
  '/$slug/admin/timeline': typeof SlugAdminTimelineRoute
  '/$slug/admin/todo': typeof SlugAdminTodoRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
  '/$slug/invite/$code': typeof SlugInviteCodeRoute
  '/admin/platform/claim': typeof AdminPlatformClaimRoute
  '/admin/platform/todo-templates': typeof AdminPlatformTodoTemplatesRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
  '/admin/platform/': typeof AdminPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/envtest': typeof EnvtestRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/guestbook': typeof SlugGuestbookRoute
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/story': typeof SlugStoryRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/admin/budget': typeof SlugAdminBudgetRoute
  '/$slug/admin/guestbook': typeof SlugAdminGuestbookRoute
  '/$slug/admin/invitation': typeof SlugAdminInvitationRoute
  '/$slug/admin/photos': typeof SlugAdminPhotosRoute
  '/$slug/admin/playlist': typeof SlugAdminPlaylistRoute
  '/$slug/admin/rsvp': typeof SlugAdminRsvpRoute
  '/$slug/admin/seating': typeof SlugAdminSeatingRoute
  '/$slug/admin/settings': typeof SlugAdminSettingsRoute
  '/$slug/admin/story': typeof SlugAdminStoryRoute
  '/$slug/admin/timeline': typeof SlugAdminTimelineRoute
  '/$slug/admin/todo': typeof SlugAdminTodoRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
  '/$slug/invite/$code': typeof SlugInviteCodeRoute
  '/admin/platform/claim': typeof AdminPlatformClaimRoute
  '/admin/platform/todo-templates': typeof AdminPlatformTodoTemplatesRoute
  '/$slug/admin': typeof SlugAdminIndexRoute
  '/admin/platform': typeof AdminPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/envtest': typeof EnvtestRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/admin': typeof SlugAdminRouteWithChildren
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/guestbook': typeof SlugGuestbookRoute
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/story': typeof SlugStoryRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/admin/platform': typeof AdminPlatformRouteWithChildren
  '/$slug/': typeof SlugIndexRoute
  '/$slug/admin/budget': typeof SlugAdminBudgetRoute
  '/$slug/admin/guestbook': typeof SlugAdminGuestbookRoute
  '/$slug/admin/invitation': typeof SlugAdminInvitationRoute
  '/$slug/admin/photos': typeof SlugAdminPhotosRoute
  '/$slug/admin/playlist': typeof SlugAdminPlaylistRoute
  '/$slug/admin/rsvp': typeof SlugAdminRsvpRoute
  '/$slug/admin/seating': typeof SlugAdminSeatingRoute
  '/$slug/admin/settings': typeof SlugAdminSettingsRoute
  '/$slug/admin/story': typeof SlugAdminStoryRoute
  '/$slug/admin/timeline': typeof SlugAdminTimelineRoute
  '/$slug/admin/todo': typeof SlugAdminTodoRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
  '/$slug/invite/$code': typeof SlugInviteCodeRoute
  '/admin/platform/claim': typeof AdminPlatformClaimRoute
  '/admin/platform/todo-templates': typeof AdminPlatformTodoTemplatesRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
  '/admin/platform/': typeof AdminPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/create'
    | '/demo'
    | '/envtest'
    | '/features'
    | '/login'
    | '/$slug/admin'
    | '/$slug/gallery'
    | '/$slug/guestbook'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/story'
    | '/$slug/timeline'
    | '/admin/platform'
    | '/$slug/'
    | '/$slug/admin/budget'
    | '/$slug/admin/guestbook'
    | '/$slug/admin/invitation'
    | '/$slug/admin/photos'
    | '/$slug/admin/playlist'
    | '/$slug/admin/rsvp'
    | '/$slug/admin/seating'
    | '/$slug/admin/settings'
    | '/$slug/admin/story'
    | '/$slug/admin/timeline'
    | '/$slug/admin/todo'
    | '/$slug/gallery/me'
    | '/$slug/invite/$code'
    | '/admin/platform/claim'
    | '/admin/platform/todo-templates'
    | '/$slug/admin/'
    | '/admin/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/demo'
    | '/envtest'
    | '/features'
    | '/login'
    | '/$slug/gallery'
    | '/$slug/guestbook'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/story'
    | '/$slug/timeline'
    | '/$slug'
    | '/$slug/admin/budget'
    | '/$slug/admin/guestbook'
    | '/$slug/admin/invitation'
    | '/$slug/admin/photos'
    | '/$slug/admin/playlist'
    | '/$slug/admin/rsvp'
    | '/$slug/admin/seating'
    | '/$slug/admin/settings'
    | '/$slug/admin/story'
    | '/$slug/admin/timeline'
    | '/$slug/admin/todo'
    | '/$slug/gallery/me'
    | '/$slug/invite/$code'
    | '/admin/platform/claim'
    | '/admin/platform/todo-templates'
    | '/$slug/admin'
    | '/admin/platform'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/create'
    | '/demo'
    | '/envtest'
    | '/features'
    | '/login'
    | '/$slug/admin'
    | '/$slug/gallery'
    | '/$slug/guestbook'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/story'
    | '/$slug/timeline'
    | '/admin/platform'
    | '/$slug/'
    | '/$slug/admin/budget'
    | '/$slug/admin/guestbook'
    | '/$slug/admin/invitation'
    | '/$slug/admin/photos'
    | '/$slug/admin/playlist'
    | '/$slug/admin/rsvp'
    | '/$slug/admin/seating'
    | '/$slug/admin/settings'
    | '/$slug/admin/story'
    | '/$slug/admin/timeline'
    | '/$slug/admin/todo'
    | '/$slug/gallery/me'
    | '/$slug/invite/$code'
    | '/admin/platform/claim'
    | '/admin/platform/todo-templates'
    | '/$slug/admin/'
    | '/admin/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  CreateRoute: typeof CreateRoute
  DemoRoute: typeof DemoRoute
  EnvtestRoute: typeof EnvtestRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  AdminPlatformRoute: typeof AdminPlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envtest': {
      id: '/envtest'
      path: '/envtest'
      fullPath: '/envtest'
      preLoaderRoute: typeof EnvtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/timeline': {
      id: '/$slug/timeline'
      path: '/timeline'
      fullPath: '/$slug/timeline'
      preLoaderRoute: typeof SlugTimelineRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/story': {
      id: '/$slug/story'
      path: '/story'
      fullPath: '/$slug/story'
      preLoaderRoute: typeof SlugStoryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/rsvp': {
      id: '/$slug/rsvp'
      path: '/rsvp'
      fullPath: '/$slug/rsvp'
      preLoaderRoute: typeof SlugRsvpRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/playlist': {
      id: '/$slug/playlist'
      path: '/playlist'
      fullPath: '/$slug/playlist'
      preLoaderRoute: typeof SlugPlaylistRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/location': {
      id: '/$slug/location'
      path: '/location'
      fullPath: '/$slug/location'
      preLoaderRoute: typeof SlugLocationRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/guestbook': {
      id: '/$slug/guestbook'
      path: '/guestbook'
      fullPath: '/$slug/guestbook'
      preLoaderRoute: typeof SlugGuestbookRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/gallery': {
      id: '/$slug/gallery'
      path: '/gallery'
      fullPath: '/$slug/gallery'
      preLoaderRoute: typeof SlugGalleryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/platform/': {
      id: '/admin/platform/'
      path: '/'
      fullPath: '/admin/platform/'
      preLoaderRoute: typeof AdminPlatformIndexRouteImport
      parentRoute: typeof AdminPlatformRoute
    }
    '/$slug/admin/': {
      id: '/$slug/admin/'
      path: '/'
      fullPath: '/$slug/admin/'
      preLoaderRoute: typeof SlugAdminIndexRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/admin/platform/todo-templates': {
      id: '/admin/platform/todo-templates'
      path: '/todo-templates'
      fullPath: '/admin/platform/todo-templates'
      preLoaderRoute: typeof AdminPlatformTodoTemplatesRouteImport
      parentRoute: typeof AdminPlatformRoute
    }
    '/admin/platform/claim': {
      id: '/admin/platform/claim'
      path: '/claim'
      fullPath: '/admin/platform/claim'
      preLoaderRoute: typeof AdminPlatformClaimRouteImport
      parentRoute: typeof AdminPlatformRoute
    }
    '/$slug/invite/$code': {
      id: '/$slug/invite/$code'
      path: '/invite/$code'
      fullPath: '/$slug/invite/$code'
      preLoaderRoute: typeof SlugInviteCodeRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/gallery/me': {
      id: '/$slug/gallery/me'
      path: '/me'
      fullPath: '/$slug/gallery/me'
      preLoaderRoute: typeof SlugGalleryMeRouteImport
      parentRoute: typeof SlugGalleryRoute
    }
    '/$slug/admin/todo': {
      id: '/$slug/admin/todo'
      path: '/todo'
      fullPath: '/$slug/admin/todo'
      preLoaderRoute: typeof SlugAdminTodoRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/timeline': {
      id: '/$slug/admin/timeline'
      path: '/timeline'
      fullPath: '/$slug/admin/timeline'
      preLoaderRoute: typeof SlugAdminTimelineRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/story': {
      id: '/$slug/admin/story'
      path: '/story'
      fullPath: '/$slug/admin/story'
      preLoaderRoute: typeof SlugAdminStoryRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/settings': {
      id: '/$slug/admin/settings'
      path: '/settings'
      fullPath: '/$slug/admin/settings'
      preLoaderRoute: typeof SlugAdminSettingsRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/seating': {
      id: '/$slug/admin/seating'
      path: '/seating'
      fullPath: '/$slug/admin/seating'
      preLoaderRoute: typeof SlugAdminSeatingRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/rsvp': {
      id: '/$slug/admin/rsvp'
      path: '/rsvp'
      fullPath: '/$slug/admin/rsvp'
      preLoaderRoute: typeof SlugAdminRsvpRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/playlist': {
      id: '/$slug/admin/playlist'
      path: '/playlist'
      fullPath: '/$slug/admin/playlist'
      preLoaderRoute: typeof SlugAdminPlaylistRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/photos': {
      id: '/$slug/admin/photos'
      path: '/photos'
      fullPath: '/$slug/admin/photos'
      preLoaderRoute: typeof SlugAdminPhotosRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/invitation': {
      id: '/$slug/admin/invitation'
      path: '/invitation'
      fullPath: '/$slug/admin/invitation'
      preLoaderRoute: typeof SlugAdminInvitationRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/guestbook': {
      id: '/$slug/admin/guestbook'
      path: '/guestbook'
      fullPath: '/$slug/admin/guestbook'
      preLoaderRoute: typeof SlugAdminGuestbookRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/budget': {
      id: '/$slug/admin/budget'
      path: '/budget'
      fullPath: '/$slug/admin/budget'
      preLoaderRoute: typeof SlugAdminBudgetRouteImport
      parentRoute: typeof SlugAdminRoute
    }
  }
}

interface SlugAdminRouteChildren {
  SlugAdminBudgetRoute: typeof SlugAdminBudgetRoute
  SlugAdminGuestbookRoute: typeof SlugAdminGuestbookRoute
  SlugAdminInvitationRoute: typeof SlugAdminInvitationRoute
  SlugAdminPhotosRoute: typeof SlugAdminPhotosRoute
  SlugAdminPlaylistRoute: typeof SlugAdminPlaylistRoute
  SlugAdminRsvpRoute: typeof SlugAdminRsvpRoute
  SlugAdminSeatingRoute: typeof SlugAdminSeatingRoute
  SlugAdminSettingsRoute: typeof SlugAdminSettingsRoute
  SlugAdminStoryRoute: typeof SlugAdminStoryRoute
  SlugAdminTimelineRoute: typeof SlugAdminTimelineRoute
  SlugAdminTodoRoute: typeof SlugAdminTodoRoute
  SlugAdminIndexRoute: typeof SlugAdminIndexRoute
}

const SlugAdminRouteChildren: SlugAdminRouteChildren = {
  SlugAdminBudgetRoute: SlugAdminBudgetRoute,
  SlugAdminGuestbookRoute: SlugAdminGuestbookRoute,
  SlugAdminInvitationRoute: SlugAdminInvitationRoute,
  SlugAdminPhotosRoute: SlugAdminPhotosRoute,
  SlugAdminPlaylistRoute: SlugAdminPlaylistRoute,
  SlugAdminRsvpRoute: SlugAdminRsvpRoute,
  SlugAdminSeatingRoute: SlugAdminSeatingRoute,
  SlugAdminSettingsRoute: SlugAdminSettingsRoute,
  SlugAdminStoryRoute: SlugAdminStoryRoute,
  SlugAdminTimelineRoute: SlugAdminTimelineRoute,
  SlugAdminTodoRoute: SlugAdminTodoRoute,
  SlugAdminIndexRoute: SlugAdminIndexRoute,
}

const SlugAdminRouteWithChildren = SlugAdminRoute._addFileChildren(
  SlugAdminRouteChildren,
)

interface SlugGalleryRouteChildren {
  SlugGalleryMeRoute: typeof SlugGalleryMeRoute
}

const SlugGalleryRouteChildren: SlugGalleryRouteChildren = {
  SlugGalleryMeRoute: SlugGalleryMeRoute,
}

const SlugGalleryRouteWithChildren = SlugGalleryRoute._addFileChildren(
  SlugGalleryRouteChildren,
)

interface SlugRouteChildren {
  SlugAdminRoute: typeof SlugAdminRouteWithChildren
  SlugGalleryRoute: typeof SlugGalleryRouteWithChildren
  SlugGuestbookRoute: typeof SlugGuestbookRoute
  SlugLocationRoute: typeof SlugLocationRoute
  SlugPlaylistRoute: typeof SlugPlaylistRoute
  SlugRsvpRoute: typeof SlugRsvpRoute
  SlugStoryRoute: typeof SlugStoryRoute
  SlugTimelineRoute: typeof SlugTimelineRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugInviteCodeRoute: typeof SlugInviteCodeRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAdminRoute: SlugAdminRouteWithChildren,
  SlugGalleryRoute: SlugGalleryRouteWithChildren,
  SlugGuestbookRoute: SlugGuestbookRoute,
  SlugLocationRoute: SlugLocationRoute,
  SlugPlaylistRoute: SlugPlaylistRoute,
  SlugRsvpRoute: SlugRsvpRoute,
  SlugStoryRoute: SlugStoryRoute,
  SlugTimelineRoute: SlugTimelineRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugInviteCodeRoute: SlugInviteCodeRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AdminPlatformRouteChildren {
  AdminPlatformClaimRoute: typeof AdminPlatformClaimRoute
  AdminPlatformTodoTemplatesRoute: typeof AdminPlatformTodoTemplatesRoute
  AdminPlatformIndexRoute: typeof AdminPlatformIndexRoute
}

const AdminPlatformRouteChildren: AdminPlatformRouteChildren = {
  AdminPlatformClaimRoute: AdminPlatformClaimRoute,
  AdminPlatformTodoTemplatesRoute: AdminPlatformTodoTemplatesRoute,
  AdminPlatformIndexRoute: AdminPlatformIndexRoute,
}

const AdminPlatformRouteWithChildren = AdminPlatformRoute._addFileChildren(
  AdminPlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  CreateRoute: CreateRoute,
  DemoRoute: DemoRoute,
  EnvtestRoute: EnvtestRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  AdminPlatformRoute: AdminPlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
