/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateRouteImport } from './routes/create'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugTimelineRouteImport } from './routes/$slug.timeline'
import { Route as SlugRsvpRouteImport } from './routes/$slug.rsvp'
import { Route as SlugPlaylistRouteImport } from './routes/$slug.playlist'
import { Route as SlugLocationRouteImport } from './routes/$slug.location'
import { Route as SlugGalleryRouteImport } from './routes/$slug.gallery'
import { Route as SlugGalleryMeRouteImport } from './routes/$slug.gallery.me'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugTimelineRoute = SlugTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SlugRoute,
} as any)
const SlugRsvpRoute = SlugRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => SlugRoute,
} as any)
const SlugPlaylistRoute = SlugPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => SlugRoute,
} as any)
const SlugLocationRoute = SlugLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGalleryRoute = SlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGalleryMeRoute = SlugGalleryMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SlugGalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/create'
    | '/demo'
    | '/features'
    | '/login'
    | '/$slug/gallery'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/timeline'
    | '/$slug/'
    | '/$slug/gallery/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/demo'
    | '/features'
    | '/login'
    | '/$slug/gallery'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/timeline'
    | '/$slug'
    | '/$slug/gallery/me'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/create'
    | '/demo'
    | '/features'
    | '/login'
    | '/$slug/gallery'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/timeline'
    | '/$slug/'
    | '/$slug/gallery/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  CreateRoute: typeof CreateRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/timeline': {
      id: '/$slug/timeline'
      path: '/timeline'
      fullPath: '/$slug/timeline'
      preLoaderRoute: typeof SlugTimelineRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/rsvp': {
      id: '/$slug/rsvp'
      path: '/rsvp'
      fullPath: '/$slug/rsvp'
      preLoaderRoute: typeof SlugRsvpRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/playlist': {
      id: '/$slug/playlist'
      path: '/playlist'
      fullPath: '/$slug/playlist'
      preLoaderRoute: typeof SlugPlaylistRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/location': {
      id: '/$slug/location'
      path: '/location'
      fullPath: '/$slug/location'
      preLoaderRoute: typeof SlugLocationRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/gallery': {
      id: '/$slug/gallery'
      path: '/gallery'
      fullPath: '/$slug/gallery'
      preLoaderRoute: typeof SlugGalleryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/gallery/me': {
      id: '/$slug/gallery/me'
      path: '/me'
      fullPath: '/$slug/gallery/me'
      preLoaderRoute: typeof SlugGalleryMeRouteImport
      parentRoute: typeof SlugGalleryRoute
    }
  }
}

interface SlugGalleryRouteChildren {
  SlugGalleryMeRoute: typeof SlugGalleryMeRoute
}

const SlugGalleryRouteChildren: SlugGalleryRouteChildren = {
  SlugGalleryMeRoute: SlugGalleryMeRoute,
}

const SlugGalleryRouteWithChildren = SlugGalleryRoute._addFileChildren(
  SlugGalleryRouteChildren,
)

interface SlugRouteChildren {
  SlugGalleryRoute: typeof SlugGalleryRouteWithChildren
  SlugLocationRoute: typeof SlugLocationRoute
  SlugPlaylistRoute: typeof SlugPlaylistRoute
  SlugRsvpRoute: typeof SlugRsvpRoute
  SlugTimelineRoute: typeof SlugTimelineRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugGalleryRoute: SlugGalleryRouteWithChildren,
  SlugLocationRoute: SlugLocationRoute,
  SlugPlaylistRoute: SlugPlaylistRoute,
  SlugRsvpRoute: SlugRsvpRoute,
  SlugTimelineRoute: SlugTimelineRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  CreateRoute: CreateRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
