/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateRouteImport } from './routes/create'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as SlugTimelineRouteImport } from './routes/$slug.timeline'
import { Route as SlugRsvpRouteImport } from './routes/$slug.rsvp'
import { Route as SlugPlaylistRouteImport } from './routes/$slug.playlist'
import { Route as SlugLocationRouteImport } from './routes/$slug.location'
import { Route as SlugGalleryRouteImport } from './routes/$slug.gallery'
import { Route as SlugAdminRouteImport } from './routes/$slug.admin'
import { Route as AdminPlatformIndexRouteImport } from './routes/admin.platform.index'
import { Route as SlugAdminIndexRouteImport } from './routes/$slug.admin.index'
import { Route as AdminPlatformTodoTemplatesRouteImport } from './routes/admin.platform.todo-templates'
import { Route as AdminPlatformClaimRouteImport } from './routes/admin.platform.claim'
import { Route as SlugGalleryMeRouteImport } from './routes/$slug.gallery.me'
import { Route as SlugAdminTodoRouteImport } from './routes/$slug.admin.todo'
import { Route as SlugAdminTimelineRouteImport } from './routes/$slug.admin.timeline'
import { Route as SlugAdminStorageRouteImport } from './routes/$slug.admin.storage'
import { Route as SlugAdminSeatingRouteImport } from './routes/$slug.admin.seating'
import { Route as SlugAdminRsvpRouteImport } from './routes/$slug.admin.rsvp'
import { Route as SlugAdminPhotosRouteImport } from './routes/$slug.admin.photos'
import { Route as SlugAdminInvitationRouteImport } from './routes/$slug.admin.invitation'
import { Route as SlugAdminGuestsRouteImport } from './routes/$slug.admin.guests'
import { Route as SlugAdminGroupsRouteImport } from './routes/$slug.admin.groups'
import { Route as SlugAdminAuditRouteImport } from './routes/$slug.admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/admin/platform',
  path: '/admin/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugTimelineRoute = SlugTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SlugRoute,
} as any)
const SlugRsvpRoute = SlugRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => SlugRoute,
} as any)
const SlugPlaylistRoute = SlugPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => SlugRoute,
} as any)
const SlugLocationRoute = SlugLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGalleryRoute = SlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SlugRoute,
} as any)
const AdminPlatformIndexRoute = AdminPlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPlatformRoute,
} as any)
const SlugAdminIndexRoute = SlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugAdminRoute,
} as any)
const AdminPlatformTodoTemplatesRoute =
  AdminPlatformTodoTemplatesRouteImport.update({
    id: '/todo-templates',
    path: '/todo-templates',
    getParentRoute: () => AdminPlatformRoute,
  } as any)
const AdminPlatformClaimRoute = AdminPlatformClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => AdminPlatformRoute,
} as any)
const SlugGalleryMeRoute = SlugGalleryMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SlugGalleryRoute,
} as any)
const SlugAdminTodoRoute = SlugAdminTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminTimelineRoute = SlugAdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminStorageRoute = SlugAdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminSeatingRoute = SlugAdminSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminRsvpRoute = SlugAdminRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminPhotosRoute = SlugAdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminInvitationRoute = SlugAdminInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminGuestsRoute = SlugAdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminGroupsRoute = SlugAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => SlugAdminRoute,
} as any)
const SlugAdminAuditRoute = SlugAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SlugAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/admin': typeof SlugAdminRouteWithChildren
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/admin/platform': typeof AdminPlatformRouteWithChildren
  '/$slug/': typeof SlugIndexRoute
  '/$slug/admin/audit': typeof SlugAdminAuditRoute
  '/$slug/admin/groups': typeof SlugAdminGroupsRoute
  '/$slug/admin/guests': typeof SlugAdminGuestsRoute
  '/$slug/admin/invitation': typeof SlugAdminInvitationRoute
  '/$slug/admin/photos': typeof SlugAdminPhotosRoute
  '/$slug/admin/rsvp': typeof SlugAdminRsvpRoute
  '/$slug/admin/seating': typeof SlugAdminSeatingRoute
  '/$slug/admin/storage': typeof SlugAdminStorageRoute
  '/$slug/admin/timeline': typeof SlugAdminTimelineRoute
  '/$slug/admin/todo': typeof SlugAdminTodoRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
  '/admin/platform/claim': typeof AdminPlatformClaimRoute
  '/admin/platform/todo-templates': typeof AdminPlatformTodoTemplatesRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
  '/admin/platform/': typeof AdminPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/admin/audit': typeof SlugAdminAuditRoute
  '/$slug/admin/groups': typeof SlugAdminGroupsRoute
  '/$slug/admin/guests': typeof SlugAdminGuestsRoute
  '/$slug/admin/invitation': typeof SlugAdminInvitationRoute
  '/$slug/admin/photos': typeof SlugAdminPhotosRoute
  '/$slug/admin/rsvp': typeof SlugAdminRsvpRoute
  '/$slug/admin/seating': typeof SlugAdminSeatingRoute
  '/$slug/admin/storage': typeof SlugAdminStorageRoute
  '/$slug/admin/timeline': typeof SlugAdminTimelineRoute
  '/$slug/admin/todo': typeof SlugAdminTodoRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
  '/admin/platform/claim': typeof AdminPlatformClaimRoute
  '/admin/platform/todo-templates': typeof AdminPlatformTodoTemplatesRoute
  '/$slug/admin': typeof SlugAdminIndexRoute
  '/admin/platform': typeof AdminPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/create': typeof CreateRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/$slug/admin': typeof SlugAdminRouteWithChildren
  '/$slug/gallery': typeof SlugGalleryRouteWithChildren
  '/$slug/location': typeof SlugLocationRoute
  '/$slug/playlist': typeof SlugPlaylistRoute
  '/$slug/rsvp': typeof SlugRsvpRoute
  '/$slug/timeline': typeof SlugTimelineRoute
  '/admin/platform': typeof AdminPlatformRouteWithChildren
  '/$slug/': typeof SlugIndexRoute
  '/$slug/admin/audit': typeof SlugAdminAuditRoute
  '/$slug/admin/groups': typeof SlugAdminGroupsRoute
  '/$slug/admin/guests': typeof SlugAdminGuestsRoute
  '/$slug/admin/invitation': typeof SlugAdminInvitationRoute
  '/$slug/admin/photos': typeof SlugAdminPhotosRoute
  '/$slug/admin/rsvp': typeof SlugAdminRsvpRoute
  '/$slug/admin/seating': typeof SlugAdminSeatingRoute
  '/$slug/admin/storage': typeof SlugAdminStorageRoute
  '/$slug/admin/timeline': typeof SlugAdminTimelineRoute
  '/$slug/admin/todo': typeof SlugAdminTodoRoute
  '/$slug/gallery/me': typeof SlugGalleryMeRoute
  '/admin/platform/claim': typeof AdminPlatformClaimRoute
  '/admin/platform/todo-templates': typeof AdminPlatformTodoTemplatesRoute
  '/$slug/admin/': typeof SlugAdminIndexRoute
  '/admin/platform/': typeof AdminPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/create'
    | '/demo'
    | '/features'
    | '/login'
    | '/$slug/admin'
    | '/$slug/gallery'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/timeline'
    | '/admin/platform'
    | '/$slug/'
    | '/$slug/admin/audit'
    | '/$slug/admin/groups'
    | '/$slug/admin/guests'
    | '/$slug/admin/invitation'
    | '/$slug/admin/photos'
    | '/$slug/admin/rsvp'
    | '/$slug/admin/seating'
    | '/$slug/admin/storage'
    | '/$slug/admin/timeline'
    | '/$slug/admin/todo'
    | '/$slug/gallery/me'
    | '/admin/platform/claim'
    | '/admin/platform/todo-templates'
    | '/$slug/admin/'
    | '/admin/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/demo'
    | '/features'
    | '/login'
    | '/$slug/gallery'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/timeline'
    | '/$slug'
    | '/$slug/admin/audit'
    | '/$slug/admin/groups'
    | '/$slug/admin/guests'
    | '/$slug/admin/invitation'
    | '/$slug/admin/photos'
    | '/$slug/admin/rsvp'
    | '/$slug/admin/seating'
    | '/$slug/admin/storage'
    | '/$slug/admin/timeline'
    | '/$slug/admin/todo'
    | '/$slug/gallery/me'
    | '/admin/platform/claim'
    | '/admin/platform/todo-templates'
    | '/$slug/admin'
    | '/admin/platform'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/create'
    | '/demo'
    | '/features'
    | '/login'
    | '/$slug/admin'
    | '/$slug/gallery'
    | '/$slug/location'
    | '/$slug/playlist'
    | '/$slug/rsvp'
    | '/$slug/timeline'
    | '/admin/platform'
    | '/$slug/'
    | '/$slug/admin/audit'
    | '/$slug/admin/groups'
    | '/$slug/admin/guests'
    | '/$slug/admin/invitation'
    | '/$slug/admin/photos'
    | '/$slug/admin/rsvp'
    | '/$slug/admin/seating'
    | '/$slug/admin/storage'
    | '/$slug/admin/timeline'
    | '/$slug/admin/todo'
    | '/$slug/gallery/me'
    | '/admin/platform/claim'
    | '/admin/platform/todo-templates'
    | '/$slug/admin/'
    | '/admin/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  CreateRoute: typeof CreateRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  AdminPlatformRoute: typeof AdminPlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/timeline': {
      id: '/$slug/timeline'
      path: '/timeline'
      fullPath: '/$slug/timeline'
      preLoaderRoute: typeof SlugTimelineRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/rsvp': {
      id: '/$slug/rsvp'
      path: '/rsvp'
      fullPath: '/$slug/rsvp'
      preLoaderRoute: typeof SlugRsvpRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/playlist': {
      id: '/$slug/playlist'
      path: '/playlist'
      fullPath: '/$slug/playlist'
      preLoaderRoute: typeof SlugPlaylistRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/location': {
      id: '/$slug/location'
      path: '/location'
      fullPath: '/$slug/location'
      preLoaderRoute: typeof SlugLocationRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/gallery': {
      id: '/$slug/gallery'
      path: '/gallery'
      fullPath: '/$slug/gallery'
      preLoaderRoute: typeof SlugGalleryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/admin': {
      id: '/$slug/admin'
      path: '/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/platform/': {
      id: '/admin/platform/'
      path: '/'
      fullPath: '/admin/platform/'
      preLoaderRoute: typeof AdminPlatformIndexRouteImport
      parentRoute: typeof AdminPlatformRoute
    }
    '/$slug/admin/': {
      id: '/$slug/admin/'
      path: '/'
      fullPath: '/$slug/admin/'
      preLoaderRoute: typeof SlugAdminIndexRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/admin/platform/todo-templates': {
      id: '/admin/platform/todo-templates'
      path: '/todo-templates'
      fullPath: '/admin/platform/todo-templates'
      preLoaderRoute: typeof AdminPlatformTodoTemplatesRouteImport
      parentRoute: typeof AdminPlatformRoute
    }
    '/admin/platform/claim': {
      id: '/admin/platform/claim'
      path: '/claim'
      fullPath: '/admin/platform/claim'
      preLoaderRoute: typeof AdminPlatformClaimRouteImport
      parentRoute: typeof AdminPlatformRoute
    }
    '/$slug/gallery/me': {
      id: '/$slug/gallery/me'
      path: '/me'
      fullPath: '/$slug/gallery/me'
      preLoaderRoute: typeof SlugGalleryMeRouteImport
      parentRoute: typeof SlugGalleryRoute
    }
    '/$slug/admin/todo': {
      id: '/$slug/admin/todo'
      path: '/todo'
      fullPath: '/$slug/admin/todo'
      preLoaderRoute: typeof SlugAdminTodoRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/timeline': {
      id: '/$slug/admin/timeline'
      path: '/timeline'
      fullPath: '/$slug/admin/timeline'
      preLoaderRoute: typeof SlugAdminTimelineRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/storage': {
      id: '/$slug/admin/storage'
      path: '/storage'
      fullPath: '/$slug/admin/storage'
      preLoaderRoute: typeof SlugAdminStorageRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/seating': {
      id: '/$slug/admin/seating'
      path: '/seating'
      fullPath: '/$slug/admin/seating'
      preLoaderRoute: typeof SlugAdminSeatingRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/rsvp': {
      id: '/$slug/admin/rsvp'
      path: '/rsvp'
      fullPath: '/$slug/admin/rsvp'
      preLoaderRoute: typeof SlugAdminRsvpRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/photos': {
      id: '/$slug/admin/photos'
      path: '/photos'
      fullPath: '/$slug/admin/photos'
      preLoaderRoute: typeof SlugAdminPhotosRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/invitation': {
      id: '/$slug/admin/invitation'
      path: '/invitation'
      fullPath: '/$slug/admin/invitation'
      preLoaderRoute: typeof SlugAdminInvitationRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/guests': {
      id: '/$slug/admin/guests'
      path: '/guests'
      fullPath: '/$slug/admin/guests'
      preLoaderRoute: typeof SlugAdminGuestsRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/groups': {
      id: '/$slug/admin/groups'
      path: '/groups'
      fullPath: '/$slug/admin/groups'
      preLoaderRoute: typeof SlugAdminGroupsRouteImport
      parentRoute: typeof SlugAdminRoute
    }
    '/$slug/admin/audit': {
      id: '/$slug/admin/audit'
      path: '/audit'
      fullPath: '/$slug/admin/audit'
      preLoaderRoute: typeof SlugAdminAuditRouteImport
      parentRoute: typeof SlugAdminRoute
    }
  }
}

interface SlugAdminRouteChildren {
  SlugAdminAuditRoute: typeof SlugAdminAuditRoute
  SlugAdminGroupsRoute: typeof SlugAdminGroupsRoute
  SlugAdminGuestsRoute: typeof SlugAdminGuestsRoute
  SlugAdminInvitationRoute: typeof SlugAdminInvitationRoute
  SlugAdminPhotosRoute: typeof SlugAdminPhotosRoute
  SlugAdminRsvpRoute: typeof SlugAdminRsvpRoute
  SlugAdminSeatingRoute: typeof SlugAdminSeatingRoute
  SlugAdminStorageRoute: typeof SlugAdminStorageRoute
  SlugAdminTimelineRoute: typeof SlugAdminTimelineRoute
  SlugAdminTodoRoute: typeof SlugAdminTodoRoute
  SlugAdminIndexRoute: typeof SlugAdminIndexRoute
}

const SlugAdminRouteChildren: SlugAdminRouteChildren = {
  SlugAdminAuditRoute: SlugAdminAuditRoute,
  SlugAdminGroupsRoute: SlugAdminGroupsRoute,
  SlugAdminGuestsRoute: SlugAdminGuestsRoute,
  SlugAdminInvitationRoute: SlugAdminInvitationRoute,
  SlugAdminPhotosRoute: SlugAdminPhotosRoute,
  SlugAdminRsvpRoute: SlugAdminRsvpRoute,
  SlugAdminSeatingRoute: SlugAdminSeatingRoute,
  SlugAdminStorageRoute: SlugAdminStorageRoute,
  SlugAdminTimelineRoute: SlugAdminTimelineRoute,
  SlugAdminTodoRoute: SlugAdminTodoRoute,
  SlugAdminIndexRoute: SlugAdminIndexRoute,
}

const SlugAdminRouteWithChildren = SlugAdminRoute._addFileChildren(
  SlugAdminRouteChildren,
)

interface SlugGalleryRouteChildren {
  SlugGalleryMeRoute: typeof SlugGalleryMeRoute
}

const SlugGalleryRouteChildren: SlugGalleryRouteChildren = {
  SlugGalleryMeRoute: SlugGalleryMeRoute,
}

const SlugGalleryRouteWithChildren = SlugGalleryRoute._addFileChildren(
  SlugGalleryRouteChildren,
)

interface SlugRouteChildren {
  SlugAdminRoute: typeof SlugAdminRouteWithChildren
  SlugGalleryRoute: typeof SlugGalleryRouteWithChildren
  SlugLocationRoute: typeof SlugLocationRoute
  SlugPlaylistRoute: typeof SlugPlaylistRoute
  SlugRsvpRoute: typeof SlugRsvpRoute
  SlugTimelineRoute: typeof SlugTimelineRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAdminRoute: SlugAdminRouteWithChildren,
  SlugGalleryRoute: SlugGalleryRouteWithChildren,
  SlugLocationRoute: SlugLocationRoute,
  SlugPlaylistRoute: SlugPlaylistRoute,
  SlugRsvpRoute: SlugRsvpRoute,
  SlugTimelineRoute: SlugTimelineRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AdminPlatformRouteChildren {
  AdminPlatformClaimRoute: typeof AdminPlatformClaimRoute
  AdminPlatformTodoTemplatesRoute: typeof AdminPlatformTodoTemplatesRoute
  AdminPlatformIndexRoute: typeof AdminPlatformIndexRoute
}

const AdminPlatformRouteChildren: AdminPlatformRouteChildren = {
  AdminPlatformClaimRoute: AdminPlatformClaimRoute,
  AdminPlatformTodoTemplatesRoute: AdminPlatformTodoTemplatesRoute,
  AdminPlatformIndexRoute: AdminPlatformIndexRoute,
}

const AdminPlatformRouteWithChildren = AdminPlatformRoute._addFileChildren(
  AdminPlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  CreateRoute: CreateRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  AdminPlatformRoute: AdminPlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
